name: backend-build
description: Build backend

inputs:
  variables-env:
    description: Variables in .env file
    required: true

runs:
  using: composite
  steps:
    - name: Run backend
      shell: bash
      run: |
        cd ./backend
        echo "${{ inputs.variables-env }}" > .production.env
        npm run start:prod
        cd ..
