name: backend-build
description: Build backend

inputs:
  variables-env:
    description: Variables in .env file
    required: true
  ssh-username:
    description: Username for SSH connection
    required: true
  ssh-host:
    description: Host for SSH connection
    required: true

runs:
  using: composite
  steps:
    - name: Copy .env files and backend code to host
      shell: bash
      run: |
        echo "${{ inputs.variables-env }}" > .production.env
        echo "${{ inputs.variables-env }}" > .development.env
        scp .production.env ${{ inputs.ssh-username }}@${{ inputs.ssh-host }}:/home/linkedout-noventiq/test-backend
        scp .development.env ${{ inputs.ssh-username }}@${{ inputs.ssh-host }}:/home/linkedout-noventiq/test-backend

    - name: Install dependencies, build, and start the backend on the VM
      shell: bash
      run: |
        ssh ${{ inputs.ssh-username }}@${{ inputs.ssh-host }} << EOF
          cd /home/linkedout-noventiq/test-backend
          npm install
          npm run build
          pm2 start dist/main.js --name backend
        EOF
