name: backend-build
description: Build backend

inputs:
  variables-env:
    description: Variables in .env file
    required: true
  ssh-username:
    description: Username for SSH connection
    required: true
  ssh-host:
    description: Host for SSH connection
    required: true

runs:
  using: composite
  steps:
    - name: Install NestJS CLI
      shell: bash
      run: |
        npm install -g @nestjs/cli

    - name: Install PM2
      shell: bash
      run: |
        npm install -g pm2

    - name: Copy .env files to host
      shell: bash
      run: |
        echo "${{ inputs.variables-env }}" > .production.env
        echo "${{ inputs.variables-env }}" > .development.env
        scp .production.env ${{ inputs.ssh-username }}@${{ inputs.ssh-host }}:/home/linkedout-noventiq/test-backend
        scp .development.env ${{ inputs.ssh-username }}@${{ inputs.ssh-host }}:/home/linkedout-noventiq/test-backend

    - name: Run backend
      shell: bash
      run: |
        cd ./backend
        echo "${{ inputs.variables-env }}" > .production.env
        echo "${{ inputs.variables-env }}" > .development.env
        npm install
        npm run build
        npm run start:prod
        cd ..
