name: backend-build
description: Build backend

inputs:
  variables-env:
    description: Variables in .env file
    required: true
  ssh-username:
    description: Username for SSH connection
    required: true
  ssh-host:
    description: Host for SSH connection
    required: true

runs:
  using: composite
  steps:
    - name: Copy .env files and backend code to host
      shell: bash
      run: |
        echo "${{ inputs.variables-env }}" > .production.env
        scp .production.env ${{ inputs.ssh-username }}@${{ inputs.ssh-host }}:/home/linkedout-noventiq/linkedout/frontend

    - name: Install dependencies, build, and start the backend on the VM
      shell: bash
      run: |
        ssh ${{ inputs.ssh-username }}@${{ inputs.ssh-host }} << EOF
          cd /home/linkedout-noventiq/linkedout/frontend
          npm install
          npm run build
          pm2 list | grep backend && pm2 restart backend || pm2 start dist/main.js --name backend
          sudo systemctl reload nginx
          sudo nginx -t
        EOF
