name: setting-ssh-to-host
description: Setting SSH connection to host

inputs:
  ssh-private-key:
    description: SSH private key to access
    required: true
  ssh-username:
    description: Username for SSH connection
    required: true
  ssh-host:
    description: Host for SSH connection
    required: true
  ssh-key-filename:
    description: Filename for SSH private key
    required: true

runs:
  using: composite
  steps:
    - name: Setup SSH agent on the runner
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Setup SSH connection to host
      env:
        SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
        SSH_USERNAME: ${{ inputs.ssh-username }}
        SSH_HOST: ${{ inputs.ssh-host }}
        SSH_KEY_FILENAME: ${{ inputs.ssh-key-filename }}
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/$SSH_KEY_FILENAME  # Store the key with the specified filename
        chmod 600 ~/.ssh/$SSH_KEY_FILENAME  # Set correct permissions
        ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts  # Add to known hosts
        ssh -i ~/.ssh/$SSH_KEY_FILENAME -o "StrictHostKeyChecking=no" $SSH_USERNAME@$SSH_HOST "echo 'Connected via SSH'"
        ssh -i ~/.ssh/$SSH_KEY_FILENAME $SSH_USERNAME@$SSH_HOST "sudo apt update"
