name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          cd frontend
          npm install
          # Check eslint version to confirm installation
          npx eslint --version
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "frontend/src/"  # Target directory for eslint
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          filter_mode: added
          fail_on_error: false
          workdir: "frontend"  # Set working directory for reviewdog
