name: reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint with reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # This makes reviewdog leave PR review comments.
          eslint_flags: 'src/**/*.ts src/**/*.tsx' # Adjust to include both .ts and .tsx files if using React